### PR TITLE
conflix

### PR DESCRIPTION
**Pull request by vtthoapl**

### CODE REVIEW

**Comment by vtthoapl** [comment]
@i create the same branch, colone and delete some of your. i just want to create conflix to learn more

**Comment by IsaMoXer** [comment]
I think here I'm supposed to tell you, after reviewing the code, where the conflicts are, and how to fix it, right? And of course, I will not allow the merging :)

**Comment by vtthoapl** [comment]
haha one way to learn that it is possible not to merge

**Comment by vtthoapl** [comment]
i will merge it by myselt on Deepika. she will have trouble then

**Pull request closed without merging**
